# Train!

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1,1],[1,2],[1,3],[1,4]])
y = np.dot(X, np.array([1,2])) + 3

lr = LinearRegression()
lr = lr.fit(X,y)
print(lr.score(X, y))

for_predict = np.array([[5,1], [0,3], [2,1], [1,1], [1,2], [9,3]])
y = lr.predict(np.array(for_predict))
print(y)

from sklearn.metrics import mean_absolute_error
y_true = [3, -0.5, 2, 7]
y_pred = [1, -0.5, 2, 8]
print(mean_absolute_error(y_true, y_pred))

1.0
[ 6. 10.  6.  6.  8. 10.]
0.75


In [2]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0)
kmeans = kmeans.fit(X)

for_predict = np.array([[5,1], [0,3], [2,1], [11,1], [9,0], [9,3]])
y = kmeans.predict(for_predict)
print(y)

[0 1 0 0 0 1]


c:\dev\conda\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\dev\conda\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [3]:
import tensorflow as tf

# Проверяем доступность GPU
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print(f"Found {len(gpus)} GPU(s)")
else:
    print("No GPU found")

Found 1 GPU(s)


In [4]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

x = np.array([.1,.2,.5,.7,.9,.10,.13])
y = np.array([1,0,1,1,1,0,1])


# Генерируем данные для обучения
x = np.random.random((10000, 5))
y = np.random.randint(2, size=(10000, 1))
y

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [5]:
# Разделяем данные на обучающую и тестовую выборки
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Создаем модель
inputs = tf.keras.Input(shape=(5,))
x = tf.keras.layers.Dense(64, activation="relu")(inputs)
x = tf.keras.layers.Dense(64, activation="relu")(x)
outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

# Компилируем модель
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Обучаем модель
model.fit(x_train, y_train, batch_size=32, epochs=300)

Epoch 1/300
250/250 [==============================] - 9s 6ms/step - loss: 0.6940 - accuracy: 0.4931
Epoch 2/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6934 - accuracy: 0.5099
Epoch 3/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6934 - accuracy: 0.5066
Epoch 4/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6928 - accuracy: 0.5099
Epoch 5/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6928 - accuracy: 0.5055
Epoch 6/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6926 - accuracy: 0.5142
Epoch 7/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6923 - accuracy: 0.5155
Epoch 8/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6921 - accuracy: 0.5150
Epoch 9/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6921 - accuracy: 0.5153
Epoch 10/300
250/250 [==============================] - 1s 5ms/step - loss: 0.6919 - accura

In [14]:
# Оцениваем модель на тестовых данных
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Loss: {int(loss*100)}%, Accuracy: {int(accuracy*100)}%")

63/63 [==============================] - 0s 4ms/step - loss: 0.7924 - accuracy: 0.4790
Loss: 79%, Accuracy: 47%


In [21]:
import tensorflow as tf

# Загрузка и предварительная обработка данных
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [15]:
# Создание модели
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

# Компиляция модели
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Обучение модели
model.fit(x_train, y_train, epochs=5)

# Оценка точности модели на тестовых данных
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)

11490434/11490434 [==============================] - 2s 0us/step
Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2992 - accuracy: 0.9131
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1455 - accuracy: 0.9564
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1076 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0860 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0746 - accuracy: 0.9764
313/313 - 1s - loss: 0.0708 - accuracy: 0.9774 - 886ms/epoch - 3ms/step

Test accuracy: 0.977400004863739
